name: Build .deb Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Quyền quan trọng để upload asset vào Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build .deb
        run: cargo deb

      - name: Upload .deb to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/debian/ecopower_*.deb
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
